import jsPDF from "jspdf";
import type { ExportDataResponse } from "@/app/actions/exports";

export function exportToPDF(data: ExportDataResponse["data"]): jsPDF {
  if (!data) throw new Error("No data to export");

  const { project, brief, comments } = data;

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const textWidth = pageWidth - margin * 2;
  let yPosition = 20;

  const addText = (text: string, isBold = false, size = 12) => {
    if (isBold) doc.setFont("helvetica", "bold");
    else doc.setFont("helvetica", "normal");
    doc.setFontSize(size);

    const lines = doc.splitTextToSize(text, 170);
    doc.text(lines, 20, yPosition);
    yPosition += lines.length * size * 0.5 + 5;
  };

  const addSection = (title: string) => {
    yPosition += 10;
    if (yPosition > 270) {
      doc.addPage();
      yPosition = 20;
    }
    doc.setFillColor(255, 198, 39); // ASU Gold
    doc.rect(20, yPosition - 5, 170, 10, "F");
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text(title, 25, yPosition + 2);
    yPosition += 15;
    doc.setTextColor(0, 0, 0);
  };

  doc.setFillColor(0, 0, 0);
  doc.rect(0, 0, 210, 30, "F");
  doc.setTextColor(255, 198, 39);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("HELIOS", 20, 15);
  doc.setFontSize(12);
  doc.text("AI Web Briefing Agent", 20, 22);
  doc.setTextColor(0, 0, 0);

  yPosition = 40;

  addText(`Project: ${project.name}`, true, 18);
  addText(`Status: ${project.status.toUpperCase()}`, false, 10);
  addText(
    `Created: ${new Date(project.createdAt).toLocaleDateString()}`,
    false,
    10
  );
  if (brief.isApproved && brief.approvedAt) {
    addText(
      `Approved: ${new Date(brief.approvedAt).toLocaleDateString()}`,
      false,
      10
    );
  }

  addSection("PURPOSE");
  addText(brief.purpose);

  addSection("TARGET AUDIENCES");
  addText("Primary Audience", true);
  addText(brief.primaryAudience);
  addText("Secondary Audience", true);
  addText(brief.secondaryAudience);

  doc.addPage();
  yPosition = 20;
  addSection("TONE & VOICE");
  addText(brief.tone);

  addSection("SITEMAP");
  brief.sitemap.forEach((page) => {
    addText(`• ${page}`, false, 11);
  });

  doc.addPage();
  yPosition = 20;

  addSection("CONSTRAINTS");
  brief.constraints.forEach((constraint) => {
    const bullet = "✓";
    const text = constraint;
    const bulletX = margin;
    const textX = margin + 6;
    const wrappedText = doc.splitTextToSize(text, textWidth - 6);

    doc.text(bullet, bulletX, yPosition);
    doc.text(wrappedText, textX, yPosition);

    yPosition += wrappedText.length * 6;
  });

  addSection("ASSUMPTIONS");
  brief.assumptions.forEach((assumption) => {
    const badge = `[${assumption.confidence.toUpperCase()}]`;
    addText(`${badge} ${assumption.text}`, false, 11);
  });

  addSection("OPEN QUESTIONS");
  brief.openQuestions.forEach((question) => {
    const bullet = "✓";
    const text = question;
    const bulletX = margin;
    const textX = margin + 6;
    const wrappedText = doc.splitTextToSize(text, textWidth - 6);

    doc.text(bullet, bulletX, yPosition);
    doc.text(wrappedText, textX, yPosition);

    yPosition += wrappedText.length * 6;
  });

  if (comments.length > 0) {
    doc.addPage();
    yPosition = 20;
    addSection("COMMENTS");

    comments.forEach((comment) => {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 20;
      }
      addText(`${comment.author} (${comment.section})`, true, 11);
      addText(`"${comment.text}"`, false, 10);
      addText(new Date(comment.createdAt).toLocaleDateString(), false, 9);
      yPosition += 5;
    });
  }

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128);
    doc.text(`Generated by Helios • Page ${i} of ${pageCount}`, 105, 290, {
      align: "center",
    });
  }

  return doc;
}
